---
- name: "Fedoraleenc post-installation Ansible playbook."
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Configure dnf
      copy:
        dest: /etc/dnf/dnf.conf
        content: |
          [main]
          gpgcheck=True
          installonly_limit=3
          clean_requirements_on_remove=True
          best=False
          skip_if_unavailable=True
          fastestmirror=True
          defaultyes=True
          max_parallel_downloads=10
          countme=False
      become: true
    - name: Add brave browser repository
      copy:
        dest: /etc/yum.repos.d/brave-browser.repo
        content: |
          [brave-browser]
          name=Brave Browser
          enabled=1
          gpgcheck=1
          autorefresh=1
          baseurl=https://brave-browser-rpm-release.s3.brave.com/$basearch
          gpgkey=https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      become: true
    - name: Add visual studio code repository
      copy:
        dest: /etc/yum.repos.d/vscode.repo
        content: |
          [vscode]
          name=Visual Studio Code
          enabled=1
          gpgcheck=1
          autorefresh=1
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc
      become: true
    - name: Add nordvpn repository
      copy:
        dest: /etc/yum.repos.d/nordvpn.repo
        content: |
          [nordvpn]
          name=Nordvpn
          enabled=1
          gpgcheck=1
          autorefresh=1
          baseurl=https://repo.nordvpn.com/yum/nordvpn/centos/x86_64
          gpgkey=https://repo.nordvpn.com/gpg/nordvpn_public.asc
      become: true
    - name: Import brave browser repository key
      rpm_key:
        state: present
        key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      become: true
    - name: Import visual studio code repository key
      rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc
      become: true
    - name: Import nordvpn repository key
      rpm_key:
        state: present
        key: https://repo.nordvpn.com/gpg/nordvpn_public.asc
      become: true
    - name: Up-to-date packages
      dnf:
        name: "*"
        state: latest
      become: true
    - name: Install RPM Fusion repositories
      dnf:
        name:
          - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
          - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm
        state: present
      become: true
    - name: Unwanted packages
      dnf:
        name:
          - rhythmbox
          - gnome-terminal
        state: absent
        autoremove: true
      become: true
    - name: Wanted packages
      dnf:
        name:
          - "@virtualization"
          - "@multimedia"
          - "@Development tools"
          - vim
          - papirus-icon-theme
          - jetbrains-mono-fonts-all
          - zsh
          - git
          - dnf-plugins-core
          - brave-browser
          - gnome-console
          - code
          - fastfetch
          - inxi
          - htop
          - btop
          - rustup
          - transmission-gtk
          - java-11-openjdk
          - java-11-openjdk-devel
          - java-11-openjdk-src
          - java-11-openjdk-javadoc
          - java-11-openjdk-jmods
          - obs-studio
          - "google-noto-*"
          - "google-roboto-*"
          - bitstream-vera-fonts-all
          - dejavu-fonts-all
          - "google-droid-*"
          - fira-code-fonts
          - "fontawesome*"
          - liberation-narrow-fonts
          - liberation-fonts
          - curl
          - cabextract
          - xorg-x11-font-utils
          - fontconfig
          - rpmfusion-free-appstream-data
          - rpmfusion-nonfree-appstream-data
          - rpmfusion-free-release-tainted
          - rpmfusion-nonfree-release-tainted
          - dnf-utils
          - nordvpn
          - gstreamer1-plugins-base
          - gstreamer1-plugins-good
          - gstreamer1-plugins-bad-free
          - gstreamer1-plugins-good-extras
          - gstreamer1-plugins-bad-free-extras
          - gstreamer1-plugins-ugly-free
          - gstreamer1-plugin-libav
          - gstreamer1-plugins-ugly
          - libdvdcss
          - gstreamer1-plugin-openh264
          - gnome-extensions-app
          - gnome-shell-extension-dash-to-dock
          - gnome-shell-extension-appindicator
        state: present
      become: true
    - name: Wanted packages (erasing existing alternatives)
      dnf:
        name:
          - intel-media-driver
          - libva-intel-driver
          - libva-intel-media-driver
          - libva
          - libva-utils
          - gstreamer1-vaapi
          - ffmpeg
          - intel-gpu-tools
          - mesa-dri-drivers
          - mesa-va-drivers-freeworld
        state: present
        allowerasing: true
      become: true
    - name: Install microsoft fonts
      dnf:
        name: https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
        state: present
      become: true

    - name: Check if volta is installed
      shell: which volta
      register: volta_installed
      failed_when: false
      changed_when: volta_installed.rc != 0
    - name: Install volta.sh
      shell: curl https://get.volta.sh | bash
      when: volta_installed.rc != 0
    - name: Check if node is installed
      shell: which node
      register: node_installed
      failed_when: false
      changed_when: node_installed.rc != 0
    - name: Install node
      shell: volta install node
      when: node_installed.rc != 0
    - name: Check if Rust is installed
      shell: which cargo
      register: rust_installed
      failed_when: false
      changed_when: rust_installed.rc != 0
    - name: Initialize Rust
      shell: rustup-init -y
      when: rust_installed.rc != 0
    - name: Enable and start libvirtd service
      systemd_service:
        name: libvirtd
        state: started
        enabled: true
      become: true
    - name: Add user to groups
      user:
        name: "{{ ansible_user_id }}"
        groups:
          - libvirt
          - video
          - audio
          - bin
          - colord
          - daemon
          - dbus
          - flatpak
          - gamemode
          - games
          - input
          - kvm
          - pipewire
          - polkitd
          - qemu
          - render
        append: yes
      become: true
