---
- name: "Fedoraleenc post-installation Ansible playbook."
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Configure sysctl
      copy:
        dest: /etc/sysctl.d/custom.conf
        content: |
          kernel.sysrq = 1
          vm.swappiness = 180
          vm.watermark_boost_factor = 0
          vm.watermark_scale_factor = 125
          vm.page-cluster = 0
      become: true
    - name: Configure environment variables
      copy:
        dest: /etc/environment
        content: |
          JAVA_HOME=/usr/lib/jvm/java
      become: true
    - name: Configure dnf
      copy:
        dest: /etc/dnf/dnf.conf
        content: |
          [main]
          gpgcheck=True
          installonly_limit=3
          clean_requirements_on_remove=True
          best=False
          skip_if_unavailable=True
          fastestmirror=True
          defaultyes=True
          max_parallel_downloads=10
          countme=False
      become: true
    - name: Add visual studio code repository
      copy:
        dest: /etc/yum.repos.d/vscode.repo
        content: |
          [vscode]
          name=Visual Studio Code
          enabled=1
          gpgcheck=1
          autorefresh=1
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc
      become: true
    - name: Import visual studio code repository key
      rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc
      become: true
    - name: Up-to-date packages
      dnf:
        name: "*"
        state: latest
      become: true
    - name: Install RPM Fusion repositories
      shell: |
        dnf install -y \
          https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
          https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
      become: true
    - name: Install RPM fusion additionnal packages
      dnf:
        name:
          - rpmfusion-free-appstream-data
          - rpmfusion-nonfree-appstream-data
          - rpmfusion-free-release-tainted
          - rpmfusion-nonfree-release-tainted
        state: present
      become: true
    - name: Wanted packages
      dnf:
        name:
          - "@virtualization"
          - "@multimedia"
          - "@Development tools"
          - "@Sound and Video"
          - vim
          - papirus-icon-theme
          - jetbrains-mono-fonts-all
          - zsh
          - git
          - dnf-plugins-core
          - gnome-console
          - code
          - fastfetch
          - inxi
          - htop
          - btop
          - rustup
          - transmission-gtk
          - java-11-openjdk
          - java-11-openjdk-devel
          - java-11-openjdk-src
          - java-11-openjdk-javadoc
          - java-11-openjdk-jmods
          - obs-studio
          - "google-roboto*"
          - "mozilla-fira*"
          - dejavu-fonts-all
          - liberation-fonts
          - liberation-narrow-fonts
          - google-noto-emoji-fonts
          - google-noto-color-emoji-fonts
          - google-noto-sans-fonts
          - google-noto-serif-fonts
          - "adobe-source-code*"
          - adobe-source-sans-pro-fonts
          - adobe-source-serif-pro-fonts
          - fontawesome-fonts-all
          - google-droid-fonts-all
          - bitstream-vera-fonts-all
          - fira-code-fonts
          - cascadia-fonts-all
          - intel-one-mono-fonts
          - curl
          - cabextract
          - xorg-x11-font-utils
          - fontconfig
          - mkfontscale
          - mkfontdir
          - xset
          - dnf-utils
          - p7zip
          - p7zip-plugins
          - unrar
          - unace
          - lha
          - gstreamer1-plugins-base
          - gstreamer1-plugins-good
          - gstreamer1-plugins-bad-free
          - gstreamer1-plugins-good-extras
          - gstreamer1-plugins-bad-free-extras
          - gstreamer1-plugins-ugly-free
          - gstreamer1-plugin-libav
          - gstreamer1-plugins-ugly
          - libdvdcss
          - gstreamer1-plugin-openh264
          - gnome-tweaks
          - gnome-extensions-app
          - gnome-shell-extension-appindicator
          - gnome-shell-extension-dash-to-dock
          - gnome-shell-extension-caffeine
          - gnome-shell-extension-gsconnect
          - nautilus-gsconnect
          - webextension-gsconnect
          - btrfs-assistant
        state: present
      become: true
    - name: Wanted packages (erasing existing alternatives)
      dnf:
        name:
          - intel-media-driver
          - libva-intel-driver
          - libva-intel-media-driver
          - libva
          - libva-utils
          - gstreamer1-vaapi
          - ffmpeg
          - intel-gpu-tools
          - mesa-dri-drivers
          - mesa-va-drivers-freeworld
          - mesa-vdpau-drivers-freeworld
        state: present
        allowerasing: true
      become: true
    - name: Wanted tainted firmware
      dnf:
        name:
          - "*-firmware"
        enablerepo: rpmfusion-nonfree-tainted
        state: present
      become: true
    - name: Install microsoft fonts
      shell: dnf install -y https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
        state: present
      become: true
    - name: Install volta.sh
      shell: "[[ -z $(which volta) ]] && curl https://get.volta.sh | bash || exit 0"
    - name: Enable and start libvirtd service
      systemd_service:
        name: libvirtd
        state: started
        enabled: true
      become: true
    - name: Add user to groups
      user:
        name: "{{ ansible_user_id }}"
        groups:
          - libvirt
          - video
          - audio
          - bin
          - colord
          - daemon
          - dbus
          - flatpak
          - gamemode
          - games
          - input
          - kvm
          - pipewire
          - polkitd
          - qemu
          - render
        append: yes
      become: true
    - name: Unwanted packages
      dnf:
        name:
          - rhythmbox
          - gnome-terminal
        state: absent
        autoremove: true
      become: true
